local M = {}

function M.setup()
	vim.cmd("highlight clear")
	if vim.fn.exists("syntax_on") == 1 then
		vim.cmd("syntax reset")
	end
	vim.g.colors_name = "mono"

	local p = require("mono.palette")
	local set = function(group, opts)
		vim.api.nvim_set_hl(0, group, opts)
	end

	-- Standard Vim UI Highlights
	set("Normal", { fg = p.fg, bg = p.bg })
	set("NormalNC", { fg = p.fg_dark, bg = p.bg })
	set("NormalFloat", { fg = p.fg, bg = p.bg_dark })
	set("FloatBorder", { fg = p.border, bg = p.bg_dark })
	set("FloatTitle", { fg = p.fg_light, bg = p.bg_dark, bold = true })
	set("FloatFooter", { fg = p.fg_dark, bg = p.bg_dark })
	set("ColorColumn", { bg = p.bg_light })
	set("Conceal", { fg = p.comment })
	set("Cursor", { fg = p.bg, bg = p.fg })
	set("lCursor", { fg = p.bg, bg = p.fg })
	set("CursorIM", { fg = p.bg, bg = p.fg })
	set("CursorColumn", { bg = p.cursor_line })
	set("CursorLine", { bg = p.cursor_line })
	set("Directory", { fg = p.fg_light, bold = true })
	set("DiffAdd", { fg = p.add })
	set("DiffChange", { fg = p.change })
	set("DiffDelete", { fg = p.delete })
	set("DiffText", { fg = p.fg_light, bg = p.bg_visual })
	set("EndOfBuffer", { fg = p.bg })
	set("TermCursor", { fg = p.bg, bg = p.fg })
	set("TermCursorNC", { fg = p.bg, bg = p.fg_dark })
	set("ErrorMsg", { fg = p.error, bold = true })
	set("WinSeparator", { fg = p.border })
	set("VertSplit", { fg = p.border })
	set("Folded", { fg = p.comment, bg = p.bg_light })
	set("FoldColumn", { fg = p.line_nr, bg = p.bg })
	set("SignColumn", { fg = p.line_nr, bg = p.bg })
	set("IncSearch", { fg = p.bg, bg = p.fg })
	set("CurSearch", { fg = p.bg, bg = p.fg_light })
	set("LineNr", { fg = p.line_nr })
	set("LineNrAbove", { fg = p.line_nr })
	set("LineNrBelow", { fg = p.line_nr })
	set("CursorLineNr", { fg = p.fg_light, bold = true })
	set("CursorLineFold", { fg = p.fg_light })
	set("CursorLineSign", { fg = p.fg_light })
	set("MatchParen", { bg = p.bg_visual, bold = true })
	set("ModeMsg", { fg = p.fg_light, bold = true })
	set("MsgArea", { fg = p.fg })
	set("MsgSeparator", { fg = p.border })
	set("MoreMsg", { fg = p.fg_light, bold = true })
	set("NonText", { fg = p.comment })
	set("Pmenu", { fg = p.fg, bg = p.bg_dark })
	set("PmenuSel", { fg = p.bg, bg = p.selection })
	set("PmenuKind", { fg = p.fg_dark, bg = p.bg_dark })
	set("PmenuKindSel", { fg = p.bg, bg = p.selection })
	set("PmenuExtra", { fg = p.fg_dark, bg = p.bg_dark })
	set("PmenuExtraSel", { fg = p.bg, bg = p.selection })
	set("PmenuSbar", { bg = p.bg_light })
	set("PmenuThumb", { bg = p.border })
	set("PmenuMatch", { fg = p.fg_light, bold = true })
	set("PmenuMatchSel", { fg = p.bg, bold = true })
	set("Question", { fg = p.info })
	set("QuickFixLine", { bg = p.bg_visual, bold = true })
	set("Search", { fg = p.bg, bg = p.fg_light })
	set("SnippetTabstop", { bg = p.bg_light })
	set("SpecialKey", { fg = p.comment })
	set("SpellBad", { underline = true, sp = p.error })
	set("SpellCap", { underline = true, sp = p.warn })
	set("SpellLocal", { underline = true, sp = p.info })
	set("SpellRare", { underline = true, sp = p.hint })
	set("StatusLine", { fg = p.fg, bg = p.bg_light })
	set("StatusLineNC", { fg = p.fg_dark, bg = p.bg_dark })
	set("TabLine", { fg = p.fg_dark, bg = p.bg_dark })
	set("TabLineFill", { bg = p.bg_dark })
	set("TabLineSel", { fg = p.fg_light, bg = p.bg, bold = true })
	set("Title", { fg = p.fg_light, bold = true })
	set("Visual", { bg = p.bg_visual })
	set("VisualNOS", { bg = p.bg_visual })
	set("WarningMsg", { fg = p.warn, bold = true })
	set("Whitespace", { fg = p.comment })
	set("WildMenu", { fg = p.bg, bg = p.selection })
	set("WinBar", { fg = p.fg, bg = p.bg })
	set("WinBarNC", { fg = p.fg_dark, bg = p.bg })

	-- Standard Syntax Groups
	set("Comment", { fg = p.comment, italic = true })
	set("Constant", { fg = p.constant })
	set("String", { fg = p.string })
	set("Character", { fg = p.string })
	set("Number", { fg = p.number })
	set("Boolean", { fg = p.constant, bold = true })
	set("Float", { fg = p.number })
	set("Identifier", { fg = p.fg })
	set("Function", { fg = p.func, bold = true })
	set("Statement", { fg = p.keyword, bold = true })
	set("Conditional", { fg = p.keyword, bold = true })
	set("Repeat", { fg = p.keyword, bold = true })
	set("Label", { fg = p.keyword })
	set("Operator", { fg = p.operator })
	set("Keyword", { fg = p.keyword, bold = true })
	set("Exception", { fg = p.keyword, bold = true })
	set("PreProc", { fg = p.special })
	set("Include", { fg = p.keyword })
	set("Define", { fg = p.special })
	set("Macro", { fg = p.special })
	set("PreCondit", { fg = p.special })
	set("Type", { fg = p.type, bold = true })
	set("StorageClass", { fg = p.keyword })
	set("Structure", { fg = p.type })
	set("Typedef", { fg = p.type })
	set("Special", { fg = p.special })
	set("SpecialChar", { fg = p.special })
	set("Tag", { fg = p.fg_light })
	set("Delimiter", { fg = p.operator })
	set("SpecialComment", { fg = p.fg_dark, bold = true })
	set("Debug", { fg = p.fg_light })
	set("Underlined", { underline = true })
	set("Ignore", { fg = p.comment })
	set("Error", { fg = p.error, bold = true })
	set("Todo", { fg = p.bg, bg = p.fg_light, bold = true })

	-- Built-in LSP Diagnostic Groups
	set("DiagnosticError", { fg = p.error })
	set("DiagnosticWarn", { fg = p.warn })
	set("DiagnosticInfo", { fg = p.info })
	set("DiagnosticHint", { fg = p.hint })
	set("DiagnosticOk", { fg = p.fg_light })

	set("DiagnosticVirtualTextError", { fg = p.error, bg = p.bg_light })
	set("DiagnosticVirtualTextWarn", { fg = p.warn, bg = p.bg_light })
	set("DiagnosticVirtualTextInfo", { fg = p.info, bg = p.bg_light })
	set("DiagnosticVirtualTextHint", { fg = p.hint, bg = p.bg_light })
	set("DiagnosticVirtualTextOk", { fg = p.fg_light, bg = p.bg_light })

	set("DiagnosticUnderlineError", { underline = true, sp = p.error })
	set("DiagnosticUnderlineWarn", { underline = true, sp = p.warn })
	set("DiagnosticUnderlineInfo", { underline = true, sp = p.info })
	set("DiagnosticUnderlineHint", { underline = true, sp = p.hint })
	set("DiagnosticUnderlineOk", { underline = true, sp = p.fg_light })

	set("DiagnosticFloatingError", { fg = p.error, bg = p.bg_dark })
	set("DiagnosticFloatingWarn", { fg = p.warn, bg = p.bg_dark })
	set("DiagnosticFloatingInfo", { fg = p.info, bg = p.bg_dark })
	set("DiagnosticFloatingHint", { fg = p.hint, bg = p.bg_dark })
	set("DiagnosticFloatingOk", { fg = p.fg_light, bg = p.bg_dark })

	set("DiagnosticSignError", { fg = p.error })
	set("DiagnosticSignWarn", { fg = p.warn })
	set("DiagnosticSignInfo", { fg = p.info })
	set("DiagnosticSignHint", { fg = p.hint })
	set("DiagnosticSignOk", { fg = p.fg_light })

	set("DiagnosticDeprecated", { strikethrough = true, fg = p.fg_dark })
	set("DiagnosticUnnecessary", { fg = p.comment })

	-- Built-in LSP Highlight Groups
	set("LspReferenceText", { bg = p.bg_visual })
	set("LspReferenceRead", { bg = p.bg_visual })
	set("LspReferenceWrite", { bg = p.bg_visual, underline = true })
	set("LspCodeLens", { fg = p.comment })
	set("LspCodeLensSeparator", { fg = p.comment })
	set("LspSignatureActiveParameter", { fg = p.fg_light, bold = true })
end

return M
