return function(p)
	return {
		-- Built-in LSP Diagnostic Groups
		DiagnosticError = { fg = p.error },
		DiagnosticWarn = { fg = p.warn },
		DiagnosticInfo = { fg = p.info },
		DiagnosticHint = { fg = p.hint },
		DiagnosticOk = { fg = p.fg_light },
		DiagnosticVirtualTextError = { fg = p.error, bg = p.bg_light },
		DiagnosticVirtualTextWarn = { fg = p.warn, bg = p.bg_light },
		DiagnosticVirtualTextInfo = { fg = p.info, bg = p.bg_light },
		DiagnosticVirtualTextHint = { fg = p.hint, bg = p.bg_light },
		DiagnosticVirtualTextOk = { fg = p.fg_light, bg = p.bg_light },
		DiagnosticUnderlineError = { underline = true, sp = p.error },
		DiagnosticUnderlineWarn = { underline = true, sp = p.warn },
		DiagnosticUnderlineInfo = { underline = true, sp = p.info },
		DiagnosticUnderlineHint = { underline = true, sp = p.hint },
		DiagnosticUnderlineOk = { underline = true, sp = p.fg_light },
		DiagnosticFloatingError = { fg = p.error, bg = p.bg_dark },
		DiagnosticFloatingWarn = { fg = p.warn, bg = p.bg_dark },
		DiagnosticFloatingInfo = { fg = p.info, bg = p.bg_dark },
		DiagnosticFloatingHint = { fg = p.hint, bg = p.bg_dark },
		DiagnosticFloatingOk = { fg = p.fg_light, bg = p.bg_dark },
		DiagnosticSignError = { fg = p.error },
		DiagnosticSignWarn = { fg = p.warn },
		DiagnosticSignInfo = { fg = p.info },
		DiagnosticSignHint = { fg = p.hint },
		DiagnosticSignOk = { fg = p.fg_light },
		DiagnosticDeprecated = { strikethrough = true, fg = p.fg_dark },
		DiagnosticUnnecessary = { fg = p.comment },
		-- Built-in LSP Highlight Groups
		LspReferenceText = { bg = p.bg_visual },
		LspReferenceRead = { bg = p.bg_visual },
		LspReferenceWrite = { bg = p.bg_visual, underline = true },
		LspCodeLens = { fg = p.comment },
		LspCodeLensSeparator = { fg = p.comment },
		LspSignatureActiveParameter = { fg = p.fg_light, bold = true },
	}
end
