return function(p) -- p for palette
	return {
		Comment = { fg = p.comment, italic = true },
		Constant = { fg = p.constant },
		String = { fg = p.string },
		Character = { fg = p.string },
		Number = { fg = p.number },
		Boolean = { fg = p.constant, bold = true },
		Float = { fg = p.number },
		Identifier = { fg = p.fg },
		Function = { fg = p.func, bold = true },
		Statement = { fg = p.keyword, bold = true },
		Conditional = { fg = p.keyword, bold = true },
		Repeat = { fg = p.keyword, bold = true },
		Label = { fg = p.keyword },
		Operator = { fg = p.operator },
		Keyword = { fg = p.keyword, bold = true },
		Exception = { fg = p.keyword, bold = true },
		PreProc = { fg = p.special },
		Include = { fg = p.keyword },
		Define = { fg = p.special },
		Macro = { fg = p.special },
		PreCondit = { fg = p.special },
		Type = { fg = p.type, bold = true },
		StorageClass = { fg = p.keyword },
		Structure = { fg = p.type },
		Typedef = { fg = p.type },
		Special = { fg = p.special },
		SpecialChar = { fg = p.special },
		Tag = { fg = p.fg_light },
		Delimiter = { fg = p.operator },
		SpecialComment = { fg = p.fg_dark, bold = true },
		Debug = { fg = p.fg_light },
		Underlined = { underline = true },
		Ignore = { fg = p.comment },
		Error = { fg = p.error, bold = true },
		Todo = { fg = p.bg, bg = p.fg_light, bold = true },
	}
end
