return function(p)
	return {
		Normal = { fg = p.fg, bg = p.bg },
		NormalNC = { fg = p.fg_dark, bg = p.bg },
		NormalFloat = { fg = p.fg, bg = p.bg_dark },
		FloatBorder = { fg = p.border, bg = p.bg_dark },
		FloatTitle = { fg = p.fg_light, bg = p.bg_dark, bold = true },
		FloatFooter = { fg = p.fg_dark, bg = p.bg_dark },
		ColorColumn = { bg = p.bg_light },
		Conceal = { fg = p.comment },
		Cursor = { fg = p.bg, bg = p.fg },
		lCursor = { fg = p.bg, bg = p.fg },
		CursorIM = { fg = p.bg, bg = p.fg },
		CursorColumn = { bg = p.cursor_line },
		CursorLine = { bg = p.cursor_line },
		Directory = { fg = p.fg_light, bold = true },
		DiffAdd = { fg = p.add },
		DiffChange = { fg = p.change },
		DiffDelete = { fg = p.delete },
		DiffText = { fg = p.fg_light, bg = p.bg_visual },
		EndOfBuffer = { fg = p.bg },
		TermCursor = { fg = p.bg, bg = p.fg },
		TermCursorNC = { fg = p.bg, bg = p.fg_dark },
		ErrorMsg = { fg = p.error, bold = true },
		WinSeparator = { fg = p.border },
		VertSplit = { fg = p.border },
		Folded = { fg = p.comment, bg = p.bg_light },
		FoldColumn = { fg = p.line_nr, bg = p.bg },
		SignColumn = { fg = p.line_nr, bg = p.bg },
		IncSearch = { fg = p.bg, bg = p.fg },
		CurSearch = { fg = p.bg, bg = p.fg_light },
		LineNr = { fg = p.line_nr },
		LineNrAbove = { fg = p.line_nr },
		LineNrBelow = { fg = p.line_nr },
		CursorLineNr = { fg = p.fg_light, bold = true },
		CursorLineFold = { fg = p.fg_light },
		CursorLineSign = { fg = p.fg_light },
		MatchParen = { bg = p.bg_visual, bold = true },
		ModeMsg = { fg = p.fg_light, bold = true },
		MsgArea = { fg = p.fg },
		MsgSeparator = { fg = p.border },
		MoreMsg = { fg = p.fg_light, bold = true },
		NonText = { fg = p.comment },
		Pmenu = { fg = p.fg, bg = p.bg_dark },
		PmenuSel = { fg = p.bg, bg = p.selection },
		PmenuKind = { fg = p.fg_dark, bg = p.bg_dark },
		PmenuKindSel = { fg = p.bg, bg = p.selection },
		PmenuExtra = { fg = p.fg_dark, bg = p.bg_dark },
		PmenuExtraSel = { fg = p.bg, bg = p.selection },
		PmenuSbar = { bg = p.bg_light },
		PmenuThumb = { bg = p.border },
		PmenuMatch = { fg = p.fg_light, bold = true },
		PmenuMatchSel = { fg = p.bg, bold = true },
		Question = { fg = p.info },
		QuickFixLine = { bg = p.bg_visual, bold = true },
		Search = { fg = p.bg, bg = p.fg_light },
		SnippetTabstop = { bg = p.bg_light },
		SpecialKey = { fg = p.comment },
		SpellBad = { underline = true, sp = p.error },
		SpellCap = { underline = true, sp = p.warn },
		SpellLocal = { underline = true, sp = p.info },
		SpellRare = { underline = true, sp = p.hint },
		StatusLine = { fg = p.fg, bg = p.bg_light },
		StatusLineNC = { fg = p.fg_dark, bg = p.bg_dark },
		TabLine = { fg = p.fg_dark, bg = p.bg_dark },
		TabLineFill = { bg = p.bg_dark },
		TabLineSel = { fg = p.fg_light, bg = p.bg, bold = true },
		Title = { fg = p.fg_light, bold = true },
		Visual = { bg = p.bg_visual },
		VisualNOS = { bg = p.bg_visual },
		WarningMsg = { fg = p.warn, bold = true },
		Whitespace = { fg = p.comment },
		WildMenu = { fg = p.bg, bg = p.selection },
		WinBar = { fg = p.fg, bg = p.bg },
		WinBarNC = { fg = p.fg_dark, bg = p.bg },
	}
end
